{{- if .Values.aws.config.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.aws.config.name }}
  namespace: {{ .Release.Namespace }}
data:
  AWS_DEFAULT_REGION: {{ .Values.aws.config.region }}
{{- end }}
