{{- if .Values.aws.credentials.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.aws.credentials.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.credentials.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.credentials.secretAccessKey }}
{{- end }}
